apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maya-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:   
    matchLabels:
      app: maya-app 
