apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maya-be-ingress
spec:
  rules:
  - host: api.maya.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maya-be-service
            port:
              number: 4000
